from __future__ import annotations

from cdm_desktop.public_api.models import ApiKeyDefinition, ProviderMeta


class ProviderRegistry:
    def __init__(self) -> None:
        self.providers = _providers()

    def all(self) -> list[ProviderMeta]:
        return list(self.providers)

    def implemented(self) -> list[ProviderMeta]:
        return [provider for provider in self.providers if provider.implemented]

    def key_definitions(self) -> list[ApiKeyDefinition]:
        items: list[ApiKeyDefinition] = []
        for provider in self.providers:
            if provider.key_name:
                items.append(
                    ApiKeyDefinition(
                        key_name=provider.key_name,
                        label=provider.display_name,
                        provider_id=provider.provider_id,
                        registration_url=provider.registration_url,
                        help_text=provider.notes or provider.purpose,
                    )
                )
        return items


def _providers() -> list[ProviderMeta]:
    return [
        ProviderMeta(
            "gleif",
            "GLEIF LEI",
            "global",
            "Global LEI legal entities",
            "LEI, legal name, registration status, jurisdiction",
            False,
            None,
            "Public free API",
            "https://www.gleif.org/en/lei-data/gleif-api",
            True,
        ),
        ProviderMeta(
            "opencorporates",
            "OpenCorporates",
            "global",
            "140+ jurisdiction company registries",
            "Company search, jurisdiction, company number",
            True,
            "OPENCORPORATES_API_TOKEN",
            "May require public benefit, trial, or paid plan",
            "https://api.opencorporates.com/documentation/API-Reference",
            True,
        ),
        ProviderMeta(
            "fmp",
            "Financial Modeling Prep",
            "financial",
            "Global listed companies and securities",
            "Symbol search, company profile, stock news",
            True,
            "FMP_API_KEY",
            "Free tier limits apply",
            "https://site.financialmodelingprep.com/register",
            True,
        ),
        ProviderMeta(
            "alpha_vantage",
            "Alpha Vantage",
            "financial",
            "Major listed securities",
            "SYMBOL_SEARCH and OVERVIEW",
            True,
            "ALPHA_VANTAGE_API_KEY",
            "Free API key; rate limits apply",
            "https://www.alphavantage.co/support/#api-key",
            True,
        ),
        ProviderMeta(
            "nasdaq_directory",
            "Nasdaq Symbol Directory",
            "financial",
            "US listed securities directory",
            "Nasdaq Trader public symbol directory fallback",
            False,
            None,
            "Public text files",
            "https://www.nasdaqtrader.com/trader.aspx?id=symboldirdefs",
            True,
        ),
        ProviderMeta(
            "marketaux",
            "Marketaux",
            "news",
            "Global financial news",
            "Company news and media mentions",
            True,
            "MARKETAUX_API_KEY",
            "Free tier limits apply",
            "https://www.marketaux.com/register",
            True,
        ),
        ProviderMeta(
            "wikidata",
            "Wikidata / Wikipedia",
            "global",
            "Public encyclopedia entities",
            "Entity labels, aliases, descriptions, Wikipedia links",
            False,
            None,
            "Public read-only API",
            "https://www.wikidata.org/wiki/Wikidata:Data_access",
            True,
            notes="Supplemental public entity source; not authoritative financial data.",
        ),
        ProviderMeta(
            "xueqiu_external",
            "雪球社区入口",
            "external_link",
            "中国大陆、港股、美股外部社区入口",
            "仅生成系统浏览器外部链接，不抓取、不缓存、不解析雪球内容",
            False,
            None,
            "无需 API key",
            "https://xueqiu.com/",
            True,
            notes="External link only; no scraping, no unofficial API, no cookie/token, no cache, no indexing.",
        ),
        ProviderMeta(
            "guardian",
            "Guardian Open Platform",
            "news",
            "Guardian news",
            "News supplement",
            True,
            "GUARDIAN_API_KEY",
            "Free key; terms apply",
            "https://open-platform.theguardian.com/access/",
            False,
            notes="v0.1.2 stub; future integration.",
        ),
        ProviderMeta(
            "newsapi",
            "NewsAPI",
            "news",
            "Global news aggregation",
            "News supplement",
            True,
            "NEWSAPI_API_KEY",
            "Strict free-tier limits",
            "https://newsapi.org/register",
            False,
            notes="v0.1.2 stub; future integration.",
        ),
        ProviderMeta(
            "companies_house",
            "UK Companies House",
            "registry",
            "United Kingdom",
            "UK company registry data",
            True,
            "COMPANIES_HOUSE_API_KEY",
            "Public API requires authentication",
            "https://developer.company-information.service.gov.uk/get-started",
            True,
        ),
        ProviderMeta(
            "insee",
            "France INSEE SIRENE",
            "registry",
            "France",
            "SIREN/SIRET legal unit data",
            True,
            "INSEE_API_KEY",
            "Authentication rules apply",
            "https://portail-api.insee.fr/",
            False,
            notes="v0.1.2 stub; authentication rules are more complex.",
        ),
        ProviderMeta(
            "abn",
            "Australia ABN Lookup",
            "registry",
            "Australia",
            "ABN validation, business name, entity status",
            True,
            "ABN_LOOKUP_GUID",
            "Official GUID registration",
            "https://abr.business.gov.au/Documentation/WebServiceRegistration",
            False,
            notes="v0.1.2 stub; future SOAP/XML mapping.",
        ),
        ProviderMeta(
            "japan_nta",
            "Japan Corporate Number",
            "registry",
            "Japan",
            "Corporate number, company name, address",
            True,
            "JAPAN_CORPORATE_NUMBER_APP_ID",
            "Free application ID",
            "https://www.houjin-bangou.nta.go.jp/webapi/index.html",
            False,
            notes="v0.1.2 stub; future integration.",
        ),
        ProviderMeta(
            "singapore_acra",
            "Singapore ACRA Open Data",
            "registry",
            "Singapore",
            "UEN, entity name, status",
            False,
            None,
            "Public data set; data.gov.sg rules apply",
            "https://data.gov.sg/dataset/acra-information-on-corporate-entities",
            False,
            notes="v0.1.2 stub; future cached public data integration.",
        ),
        ProviderMeta(
            "norway_brreg",
            "Norway BRREG",
            "registry",
            "Norway",
            "Organization number, legal name, address",
            False,
            None,
            "Public API",
            "https://data.brreg.no/enhetsregisteret/api/dokumentasjon/en/index.html",
            True,
        ),
        ProviderMeta(
            "canada_corporations",
            "Corporations Canada",
            "registry",
            "Canada",
            "Federal corporation profile",
            True,
            "CANADA_CORPORATIONS_API_KEY",
            "Requires API Store Public Plan",
            "https://api.ised-isde.canada.ca/en/docs?api=corporations",
            False,
            notes="v0.1.2 stub; requires official Public Plan.",
        ),
        ProviderMeta(
            "rss",
            "RSS / Atom News",
            "news",
            "User-configured public RSS",
            "News fallback",
            False,
            None,
            "Public RSS",
            "https://www.rssboard.org/rss-specification",
            True,
        ),
    ]
