from __future__ import annotations

from cdm_desktop.public_api.models import ApiKeyDefinition, ProviderMeta


class ProviderRegistry:
    def __init__(self) -> None:
        self.providers = _providers()

    def all(self) -> list[ProviderMeta]:
        return list(self.providers)

    def implemented(self) -> list[ProviderMeta]:
        return [provider for provider in self.providers if provider.implemented]

    def key_definitions(self) -> list[ApiKeyDefinition]:
        items: list[ApiKeyDefinition] = []
        for provider in self.providers:
            if provider.key_name:
                items.append(
                    ApiKeyDefinition(
                        key_name=provider.key_name,
                        label=provider.display_name,
                        provider_id=provider.provider_id,
                        registration_url=provider.registration_url,
                        help_text=provider.notes or provider.purpose,
                    )
                )
        return items


def _providers() -> list[ProviderMeta]:
    return [
        ProviderMeta(
            "china_hk_symbol_index",
            "中国及港股公开数据",
            "symbol_universe",
            "Bundled A-share and Hong Kong security master index",
            "中文名称、简称、A股和港股代码离线搜索；不是实时行情源。",
            False,
            None,
            "Bundled open-source index",
            "https://github.com/akfamily/akshare",
            True,
            notes="随安装包分发，无需 API key；运行时 AKShare 补全为 experimental。",
        ),
        ProviderMeta(
            "symbol_universe",
            "内置开源证券索引",
            "symbol_universe",
            "Bundled FinanceDatabase-generated equities index",
            "本地内置 symbol universe，用于公司名、代码和交易所元数据搜索；不是实时行情源。",
            False,
            None,
            "Bundled open-source index",
            "https://github.com/JerBouma/FinanceDatabase",
            True,
            notes="随安装包分发的轻量 SQLite 索引；普通用户无需 Python、pip install 或 API key。",
        ),
        ProviderMeta(
            "finance_database",
            "FinanceDatabase Symbol Universe",
            "symbol_universe",
            "Build-time symbol universe source",
            "Legacy/runtime optional provider kept for compatibility; normal users use the bundled symbol_universe index",
            False,
            None,
            "Build-time open-source dependency",
            "https://github.com/JerBouma/FinanceDatabase",
            True,
            enabled_by_default=False,
            notes="Legacy optional provider. Runtime default uses bundled symbol_universe index instead of requiring FinanceDatabase installation.",
        ),
        ProviderMeta(
            "akshare",
            "中国及港股公开数据（运行时补充）",
            "experimental",
            "China A-share and Hong Kong public lists",
            "Experimental no-key Chinese symbol/name search where public interfaces are available",
            False,
            None,
            "Bundled open-source dependency",
            "https://github.com/akfamily/akshare",
            True,
            notes="Bundled experimental no-key provider; lazy-loaded only for detail enrichment. No login, cookie, token, or anti-bot bypass.",
        ),
        ProviderMeta(
            "gleif",
            "GLEIF LEI",
            "global",
            "Global LEI legal entities",
            "LEI, legal name, registration status, jurisdiction",
            False,
            None,
            "Public free API",
            "https://www.gleif.org/en/lei-data/gleif-api",
            True,
        ),
        ProviderMeta(
            "opencorporates",
            "OpenCorporates",
            "global",
            "140+ jurisdiction company registries",
            "Company search, jurisdiction, company number",
            True,
            "OPENCORPORATES_API_TOKEN",
            "May require public benefit, trial, or paid plan",
            "https://api.opencorporates.com/documentation/API-Reference",
            True,
            enabled_by_default=False,
            notes="Advanced / legacy API provider.普通用户默认无需配置。",
        ),
        ProviderMeta(
            "fmp",
            "Financial Modeling Prep",
            "financial",
            "Global listed companies and securities",
            "Symbol search, company profile, stock news",
            True,
            "FMP_API_KEY",
            "Free tier limits apply",
            "https://site.financialmodelingprep.com/register",
            True,
            enabled_by_default=False,
            notes="Advanced / legacy free API provider.普通用户默认无需配置。",
        ),
        ProviderMeta(
            "alpha_vantage",
            "Alpha Vantage",
            "financial",
            "Major listed securities",
            "SYMBOL_SEARCH and OVERVIEW",
            True,
            "ALPHA_VANTAGE_API_KEY",
            "Free API key; rate limits apply",
            "https://www.alphavantage.co/support/#api-key",
            True,
            enabled_by_default=False,
            notes="Advanced / legacy free API provider.普通用户默认无需配置。",
        ),
        ProviderMeta(
            "nasdaq_directory",
            "Nasdaq Symbol Directory",
            "financial",
            "US listed securities directory",
            "Nasdaq Trader public symbol directory fallback",
            False,
            None,
            "Public text files",
            "https://www.nasdaqtrader.com/trader.aspx?id=symboldirdefs",
            True,
        ),
        ProviderMeta(
            "marketaux",
            "Marketaux",
            "news",
            "Global financial news",
            "Company news and media mentions",
            True,
            "MARKETAUX_API_KEY",
            "Free tier limits apply",
            "https://www.marketaux.com/register",
            True,
            enabled_by_default=False,
            notes="Advanced / legacy free API provider.普通用户默认无需配置。",
        ),
        ProviderMeta(
            "wikidata",
            "Wikidata / Wikipedia",
            "global",
            "Public encyclopedia entities",
            "Entity labels, aliases, descriptions, Wikipedia links",
            False,
            None,
            "Public read-only API",
            "https://www.wikidata.org/wiki/Wikidata:Data_access",
            True,
            notes="Supplemental public entity source; not authoritative financial data.",
        ),
        ProviderMeta(
            "xueqiu_external",
            "雪球社区入口",
            "external_link",
            "中国大陆、港股、美股外部社区入口",
            "仅生成系统浏览器外部链接，不抓取、不缓存、不解析雪球内容",
            False,
            None,
            "无需 API key",
            "https://xueqiu.com/",
            True,
            notes="External link only; no scraping, no unofficial API, no cookie/token, no cache, no indexing.",
        ),
        ProviderMeta(
            "crawlergo_web_evidence",
            "网页证据采集",
            "web_evidence",
            "公司官网和授权公开页面证据采集",
            "用户手动触发；尊重 robots.txt；默认只展示短摘录、元数据和原文链接。",
            False,
            None,
            "Optional crawlergo binary",
            "https://github.com/Qianlitp/crawlergo",
            True,
            notes="Optional binary integration. No login bypass, captcha bypass, social-content crawling, third-party full-text cache, or AI/RAG ingestion.",
        ),
        ProviderMeta(
            "guardian",
            "Guardian Open Platform",
            "news",
            "Guardian news",
            "News supplement",
            True,
            "GUARDIAN_API_KEY",
            "Free key; terms apply",
            "https://open-platform.theguardian.com/access/",
            False,
            notes="Stub / future: future integration.",
        ),
        ProviderMeta(
            "newsapi",
            "NewsAPI",
            "news",
            "Global news aggregation",
            "News supplement",
            True,
            "NEWSAPI_API_KEY",
            "Strict free-tier limits",
            "https://newsapi.org/register",
            False,
            notes="Stub / future: future integration.",
        ),
        ProviderMeta(
            "companies_house",
            "UK Companies House",
            "registry",
            "United Kingdom",
            "UK company registry data",
            True,
            "COMPANIES_HOUSE_API_KEY",
            "Public API requires authentication",
            "https://developer.company-information.service.gov.uk/get-started",
            True,
            enabled_by_default=False,
            notes="Advanced registry API provider.普通用户默认无需配置。",
        ),
        ProviderMeta(
            "insee",
            "France INSEE SIRENE",
            "registry",
            "France",
            "SIREN/SIRET legal unit data",
            True,
            "INSEE_API_KEY",
            "Authentication rules apply",
            "https://portail-api.insee.fr/",
            False,
            notes="Stub / future: authentication rules are more complex.",
        ),
        ProviderMeta(
            "abn",
            "Australia ABN Lookup",
            "registry",
            "Australia",
            "ABN validation, business name, entity status",
            True,
            "ABN_LOOKUP_GUID",
            "Official GUID registration",
            "https://abr.business.gov.au/Documentation/WebServiceRegistration",
            False,
            notes="Stub / future: future SOAP/XML mapping.",
        ),
        ProviderMeta(
            "japan_nta",
            "Japan Corporate Number",
            "registry",
            "Japan",
            "Corporate number, company name, address",
            True,
            "JAPAN_CORPORATE_NUMBER_APP_ID",
            "Free application ID",
            "https://www.houjin-bangou.nta.go.jp/webapi/index.html",
            False,
            notes="Stub / future: future integration.",
        ),
        ProviderMeta(
            "singapore_acra",
            "Singapore ACRA Open Data",
            "registry",
            "Singapore",
            "UEN, entity name, status",
            False,
            None,
            "Public data set; data.gov.sg rules apply",
            "https://data.gov.sg/dataset/acra-information-on-corporate-entities",
            False,
            notes="Stub / future: future cached public data integration.",
        ),
        ProviderMeta(
            "norway_brreg",
            "Norway BRREG",
            "registry",
            "Norway",
            "Organization number, legal name, address",
            False,
            None,
            "Public API",
            "https://data.brreg.no/enhetsregisteret/api/dokumentasjon/en/index.html",
            True,
        ),
        ProviderMeta(
            "canada_corporations",
            "Corporations Canada",
            "registry",
            "Canada",
            "Federal corporation profile",
            True,
            "CANADA_CORPORATIONS_API_KEY",
            "Requires API Store Public Plan",
            "https://api.ised-isde.canada.ca/en/docs?api=corporations",
            False,
            notes="Stub / future: requires official Public Plan.",
        ),
        ProviderMeta(
            "rss",
            "RSS / Atom News",
            "news",
            "User-configured public RSS",
            "News fallback",
            False,
            None,
            "Public RSS",
            "https://www.rssboard.org/rss-specification",
            True,
        ),
    ]
